### PR TITLE
Feature/cleanup

### PR DESCRIPTION
**Pull request by yunzc**
- [x] Restructure to include and src folders 
- [x] Install header files

### CODE REVIEW

**Comment by ToniRV** [comment]
I like the restructuring! Thanks! 

The PR is a bit too long for me to review fully now, but are there any API changes that would break compatibility? Can you try running Kimera-VIO?

**Comment by yunzc** [comment]
Actually hold off on reviewing for now. I am testing the header install with Kimera-VIO and Kimera-VIO ROS to confirm that it wouldn't break compatibility. I'll update you once I tested it! Thanks!

**Comment by yunzc** [comment]
@ToniRV Does not break compatibility for me. Could you check it on your machine when you have the chance though? Thanks

**Comment by ToniRV** [comment]
Trying now, thanks!

**Comment by ToniRV** [comment]
Seems to work for me as well, although not sure why I'm not seeing the pose-graph visualization in rviz? Did we update pose_graph_tools and/or the rviz config in kimera-vio-ros?

**Comment by yunzc** [comment]
Good question, seeing that as well, I can check. Could also be that it doesn't publish if lcd is not on? I'll double check.

**Comment by yunzc** [comment]
@ToniRV checked that pose-graph visualization is working for me. You were probably not seeing pose-graph because lcd was off (only publishes if lcd on). Is this ok to merge?

**Comment by Wallbraker** [comment]
Ping?

**Comment by ToniRV** [comment]
@yunzc ?

**Comment by yunzc** [comment]
> @yunzc ?

@ToniRV Will merge once double checking for compatibility with current vio master

**Pull request merged**
