### PR TITLE
rename all RobustPGO to Kimera-RPGO

### PR DESCRIPTION
**Pull request by yunzc**

### CODE REVIEW

**Comment by ToniRV** [comment]
@yunzc I wouldn't have merged to master that fast since now all the Kimera modules that depend on RPGO will be broken. We should have updated master altogether.

**Comment by marcusabate** [comment]
May be worth reverting until we fix the other repos?

**Comment by yunzc** [comment]
alright reverting

**Comment by yunzc** [comment]
Actually reverting should be ugly. Could you just use the previous commit?

**Pull request merged**
